version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "17:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.1
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.1
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.12.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: "@mdx-js/mdx"
    versions:
    - 1.6.22
  - dependency-name: "@codinators/gatsby-shared-library"
    versions:
    - 1.6.2
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.1
  - dependency-name: "@codinators/eslint-config"
    versions:
    - 1.1.0
  - dependency-name: typeface-inter
    versions:
    - 3.15.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.11.2
    - 2.13.4
    - 2.14.3
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.11.1
    - 5.19.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.1
    - 4.15.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: "@types/react"
    versions:
    - 16.14.4
    - 17.0.0
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.20.0
    - 1.20.2
    - 1.21.0
  - dependency-name: gatsby
    versions:
    - 2.29.3
    - 2.31.1
    - 2.32.8
  - dependency-name: "@graphql-codegen/cli"
    versions:
    - 1.20.0
    - 1.20.1
    - 1.21.1
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: markdownlint-cli
    versions:
    - 0.26.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: babel-loader
    versions:
    - 8.2.2
