overwrite: true
schema: http://localhost:8000/___graphql
documents:
    - ./src/**/*.{ts,tsx}
    - ./gatsby/*.js
    - ../node_modules/gatsby*/!(node_modules)/**/*.js
generates:
    ./src/graphqlTypes.ts:
        plugins:
            - typescript
            - typescript-operations
        config:
            maybeValue: T | undefined
            skipTypename: true

hooks:
    afterAllFileWrite:
        - prettier --write
        - eslint --fix
