schema: http://localhost:8000/___graphql
documents:
    - ./src/**/*.{ts,tsx}
    - ./node_modules/gatsby-*/**/*.js
generates:
    ./src/graphqlTypes.ts:
        plugins:
            - typescript
            - typescript-operations
config:
    maybeValue: T | undefined
    skipTypename: true

hooks:
    afterAllFileWrite:
        - prettier --write
        - eslint --fix
